### PR TITLE
fix: cinder_limits_volume_used_gb metric

### LINKED ISSUE #92: Bug for cinder `limits_volume_used_gb`
In [`sql/cinder/queries.sql`](https://github.com/vexxhost/openstack_database_exporter/blob/4be202289059af3811dfbcf439c378a9641631fc/sql/cinder/queries.sql#L21), we have:

```sql
-- name: GetProjectQuotaLimits :many
SELECT
    q.project_id,
    q.resource,
    q.hard_limit,
    COALESCE(qu.in_use, 0) as in_use
FROM
    quotas q
    LEFT JOIN quota_usages qu ON q.project_id = qu.project_id
        AND q.resource = qu.resource
        AND qu.deleted = 0
WHERE
    q.deleted = 0
    AND (q.resource IN ('gigabytes', 'backup_gigabytes') OR q.resource LIKE 'gigabytes\_%');
```

If the project has no entry with resource "gigabytes" in `quotas`, any entry for that project in `quota_usages` of resource gigabytes gets ignored / overridden and the metric will have a value of 0, even though the `quota_usages` has a non-zero count for gigabytes. I noticed this while comparing diffs between Niedbalski exporter and this exporter.

The "gigabytes" the Niedbalski exporter is exporting is the "gigabytes" you see with:
```
openstack quota show --usage <PROJECT_ID>
```
It is a SUM of gigabytes (gigabytes_standard, gigabytes_performance, etc) all also found in `quota_usages`. 
What seems to work would be a split into two queries:

```sql
-- name: GetProjectQuotaUsages :many
SELECT 
    q.project_id,
    qu.resource,
    COALESCE(qu.in_use,0) AS in_use,
    q.hard_limit
FROM 
    quotas q 
    LEFT JOIN quota_usages qu ON q.project_id=qu.project_id 
    AND qu.deleted=0 
WHERE 
    q.deleted=0 
    AND (qu.resource IN ('gigabytes', 'backup_gigabytes'));

-- name: GetProjectQuotaLimits :many
SELECT 
    q.project_id, 
    q.resource, 
    q.hard_limit 
FROM 
    quotas q 
WHERE 
    q.deleted = 0 
    AND (q.resource IN ('gigabytes', 'backup_gigabytes') 
    OR q.resource LIKE 'gigabytes\\_%');
```
You can then use `GetProjectQuotaUsages` to export the correct usages for metric `limits_volume_used_gb` of all projects and `GetProjectQuotaLimits` for the metric `volume_type_quota_gigabytes`.

This is just a suggestion; there could be still a case I missed.

### PR DESCRIPTION
**Pull request by fitbeard**
Fixes: https://github.com/vexxhost/openstack_database_exporter/issues/92

Limits → read hard_limit from quotas (which only exists when explicitly set)
Usage → read in_use directly from quota_usages (which always exists when resources are consumed)

### CODE REVIEW

File: internal/collector/cinder/limits.go [hunk 1]
```diff
@@ -134,15 +141,29 @@ func (c *LimitsCollector) Collect(ch chan<- prometheus.Metric) {
...
 			pq.hasVolume = true
 		case "backup_gigabytes":
 			pq.backupMaxGB = quota.HardLimit.Int32
-			pq.backupUsedGB = quota.InUse
 			pq.hasBackup = true
 		}
 	}
 
+	// Overlay usage data from quota_usages table
+	for _, usage := range quotaUsages {
```
Comment (na50r) [inline internal/collector/cinder/limits.go:152]: If quota_usages table has more projects/tenants than quotas, could this not end up with usage metrics of projects that do not exist anymore? 

I.e., you may get metrics for `openstack_cinder_limits_volume_used_gp` and `openstack_cinder_volume_type_quota_gigabytes` for projects that cannot be found with `openstack project show <project_id>`

If this was intended, all good.

Comment (fitbeard) [reply internal/collector/cinder/limits.go:152]: The concern is valid but this behavior is intentional and pre-existing. Projects with orphaned usage should still surface in metrics since they represent real resource consumption. The `projectResolver` already gracefully handles projects not found in keystone by falling back to the project ID as the name.

The volumes still exist on disk, consuming real storage
The quota_usages row still says in_use = 11
Keystone just won't resolve the UUID to a name anymore

That's actually useful — an operator sees "this unknown project is still consuming 11 GB" and knows they need to clean up orphaned resources. Hiding it (reporting 0) would be worse.

@mnaser your thoughts?
